// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ClearRequestLogs() {
  return window['go']['service']['App']['ClearRequestLogs']();
}

export function ConnectSocket(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['service']['App']['ConnectSocket'](arg1, arg2, arg3, arg4, arg5);
}

export function DeleteRequestLog(arg1) {
  return window['go']['service']['App']['DeleteRequestLog'](arg1);
}

export function DisconnectSocket(arg1) {
  return window['go']['service']['App']['DisconnectSocket'](arg1);
}

export function ExecuteJs(arg1) {
  return window['go']['service']['App']['ExecuteJs'](arg1);
}

export function GetALLLang() {
  return window['go']['service']['App']['GetALLLang']();
}

export function GetCurrentLang() {
  return window['go']['service']['App']['GetCurrentLang']();
}

export function GetLangPack() {
  return window['go']['service']['App']['GetLangPack']();
}

export function GetLangTextMap() {
  return window['go']['service']['App']['GetLangTextMap']();
}

export function GetLogFileContent(arg1) {
  return window['go']['service']['App']['GetLogFileContent'](arg1);
}

export function GetLogFiles() {
  return window['go']['service']['App']['GetLogFiles']();
}

export function GetLogLevel() {
  return window['go']['service']['App']['GetLogLevel']();
}

export function GetProcessName() {
  return window['go']['service']['App']['GetProcessName']();
}

export function GetProxy() {
  return window['go']['service']['App']['GetProxy']();
}

export function GetProxyAddress() {
  return window['go']['service']['App']['GetProxyAddress']();
}

export function GetRequestLog(arg1) {
  return window['go']['service']['App']['GetRequestLog'](arg1);
}

export function GetRequestLogs() {
  return window['go']['service']['App']['GetRequestLogs']();
}

export function GetTimeout() {
  return window['go']['service']['App']['GetTimeout']();
}

export function GetVersion() {
  return window['go']['service']['App']['GetVersion']();
}

export function IsSocketConnected(arg1) {
  return window['go']['service']['App']['IsSocketConnected'](arg1);
}

export function Notify(arg1, arg2) {
  return window['go']['service']['App']['Notify'](arg1, arg2);
}

export function OpenFileSelect() {
  return window['go']['service']['App']['OpenFileSelect']();
}

export function OpenFolderSelect() {
  return window['go']['service']['App']['OpenFolderSelect']();
}

export function ReadFileContent(arg1) {
  return window['go']['service']['App']['ReadFileContent'](arg1);
}

export function SaveFileSelect() {
  return window['go']['service']['App']['SaveFileSelect']();
}

export function SearchRequestLogs(arg1) {
  return window['go']['service']['App']['SearchRequestLogs'](arg1);
}

export function SendHttpRequest(arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8, arg9, arg10, arg11, arg12) {
  return window['go']['service']['App']['SendHttpRequest'](arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8, arg9, arg10, arg11, arg12);
}

export function SendSocketMessage(arg1, arg2) {
  return window['go']['service']['App']['SendSocketMessage'](arg1, arg2);
}

export function SetLanguage(arg1) {
  return window['go']['service']['App']['SetLanguage'](arg1);
}

export function SetLogLevel(arg1) {
  return window['go']['service']['App']['SetLogLevel'](arg1);
}

export function SetProxy(arg1) {
  return window['go']['service']['App']['SetProxy'](arg1);
}

export function SetTimeout(arg1) {
  return window['go']['service']['App']['SetTimeout'](arg1);
}

export function WindowClose() {
  return window['go']['service']['App']['WindowClose']();
}

export function WindowMinimise() {
  return window['go']['service']['App']['WindowMinimise']();
}

export function WindowToggleMaximise() {
  return window['go']['service']['App']['WindowToggleMaximise']();
}

export function WriteFileContent(arg1, arg2) {
  return window['go']['service']['App']['WriteFileContent'](arg1, arg2);
}
