// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {api} from '../models';
import {global} from '../models';
import {service} from '../models';

export function ClearRequestLogs():Promise<boolean>;

export function ConnectSocket(arg1:string,arg2:string,arg3:number,arg4:string,arg5:string):Promise<boolean>;

export function DeleteRequestLog(arg1:number):Promise<boolean>;

export function DisconnectSocket(arg1:string):Promise<boolean>;

export function ExecuteJs(arg1:string):Promise<api.JsExecResult>;

export function GetALLLang():Promise<Array<global.LanguageInfo>>;

export function GetCurrentLang():Promise<string>;

export function GetLangPack():Promise<global.LanguagePack>;

export function GetLangTextMap():Promise<Record<string, string>>;

export function GetLogFileContent(arg1:string):Promise<string>;

export function GetLogFiles():Promise<Array<string>>;

export function GetLogLevel():Promise<string>;

export function GetProcessName():Promise<string>;

export function GetProxy():Promise<service.ProxyConfig>;

export function GetProxyAddress():Promise<string>;

export function GetRequestLog(arg1:number):Promise<api.RequestLog>;

export function GetRequestLogs():Promise<Array<api.RequestLog>>;

export function GetTimeout():Promise<service.TimeoutConfig>;

export function GetVersion():Promise<string>;

export function IsSocketConnected(arg1:string):Promise<boolean>;

export function Notify(arg1:string,arg2:string):Promise<void>;

export function OpenFileSelect():Promise<string>;

export function OpenFolderSelect():Promise<string>;

export function ReadFileContent(arg1:string):Promise<string>;

export function SaveFileSelect():Promise<string>;

export function SearchRequestLogs(arg1:string):Promise<Array<api.RequestLog>>;

export function SendHttpRequest(arg1:string,arg2:string,arg3:string,arg4:string,arg5:string,arg6:string,arg7:string,arg8:string,arg9:string,arg10:number,arg11:boolean,arg12:boolean):Promise<api.HttpResponse>;

export function SendSocketMessage(arg1:string,arg2:string):Promise<boolean>;

export function SetLanguage(arg1:string):Promise<boolean>;

export function SetLogLevel(arg1:string):Promise<boolean>;

export function SetProxy(arg1:string):Promise<boolean>;

export function SetTimeout(arg1:number):Promise<boolean>;

export function WindowClose():Promise<void>;

export function WindowMinimise():Promise<void>;

export function WindowToggleMaximise():Promise<void>;

export function WriteFileContent(arg1:string,arg2:string):Promise<boolean>;
